services:
  redis:
    container_name: redis
    image: redislabs/rejson:2.0.11
    restart: always
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - redis-data:/data
      - ./redis/:/usr/local/etc/redis
    command: ['/usr/local/etc/redis/redis.conf', '--requirepass $REDIS_PASSPHRASE']

  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOST=redis
      - REDIS_PASSWORD=$REDIS_PASSPHRASE
      - HTTP_USER=$REDISCMD_USER
      - HTTP_PASSWORD=$REDISCMD_PASSWORD
      - NO_LOG_DATA=1
    ports:
      - '127.0.0.1:6380:8081'
    links:
      - redis

volumes:
  redis-data:
