test:
  stage: test
  rules:
    - !reference [.shared_config, rules, no_tags]
    - !reference [.shared_config, rules, web_and_push_and_schedule]
    - when: on_success
  cache:
    - !reference [.shared_config, cache, node_modules]
  script:
    - npm audit
    - npm run lint
    - npm run typecheck
    - npm run test-units
